name: thecocktailbar_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

#-------------------Packages---------------#
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4


#Utilities

http: ^1.2.2
intl: ^0.20.1
logger: ^2.5.0
url_launcher: ^6.3.1

#Icons
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.//
iconsax: ^0.0.8
cupertino_icons: ^1.0.8

  #State Management
get: ^4.6.6
get_storage: ^2.1.1

  #Product Specific



  #----------------------/Packages end---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 

flutter:   
  uses-material-design: true

  #------------Local assets--------------#
  assets:
  - assets/logos/
  - assets/icons/
  - assets/images/

  #---------------local fonts---------------#

  fonts: 
    - family: Poppins
      fonts:
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts\Poppins-Light.ttf
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts\Poppins-Regular.ttf
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts\Poppins-Italic.ttf
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts-Medium.ttf
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts\Poppins-MediumItalic.ttf
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts\Poppins-SemiBold.ttf
       - asset: C:\Users\user\Documents\TheBar_App\thecocktailbar_app\assets\fonts\Poppins-Bold.ttf
        


  